server:
  port: 8881
  undertow:
    threads:
      io: 4
      worker: 200
    buffer-size: 1024
    direct-buffers: true
#  servlet:
#    context-path: /gateway
logging:
  file:
    name: ${spring.application.name}
    path: /Users/andrew/logs/${spring.application.name}
  config: classpath:log4j2.xml
spring:
  cloud:
    gateway:
      routes:
        - id: service-2
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/service-2/**
        #          filters:
        #            - StripPrefix=1
        #            - PrefixPath=/service-2
        #            - RewritePath=/service-3/(?<segment>.*), /service-3/service-3/$\{segment}
        - id: monitor-admin-server-nacos
          uri: lb://monitor-admin-server-nacos
          predicates:
            - Path=/monitor-admin-server-nacos
  boot:
    admin:
      client:
        url: http://127.0.0.1:8801
#        metadata:
#          management:
#            context-path: ${server.servlet.context-path}/actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always